### ISSUE TITLE
sphinx.errors.ThemeError: no theme named 'sphinx_rtd_theme' found (missing theme.toml?)

### ISSUE THREAD

**Issue by alexanderilyin** [swyddfa/esbonio#923]
### Expected behavior

Live Preview works.

### Actual behavior

Live Preview does not work.

### Log output

```shell
Running Sphinx v8.1.3
loading translations [en]...
done
Converting `source_suffix = '.rst'` to `source_suffix = {'.rst': 'restructuredtext'}`.
[esbonio.lsp] Traceback (most recent call last):
  File "/home/vscode/.local/lib/python3.10/site-packages/esbonio/lsp/sphinx/__init__.py", line 152, in _initialize_sphinx
    return self.create_sphinx_app(self.user_config)  # type: ignore
  File "/home/vscode/.local/lib/python3.10/site-packages/esbonio/lsp/sphinx/__init__.py", line 343, in create_sphinx_app
    app = Sphinx(**self.sphinx_args)
  File "/home/vscode/.local/lib/python3.10/site-packages/sphinx/application.py", line 295, in __init__
    self._init_builder()
  File "/home/vscode/.local/lib/python3.10/site-packages/sphinx/application.py", line 368, in _init_builder
    self.builder.init()
  File "/home/vscode/.local/lib/python3.10/site-packages/sphinx/builders/html/__init__.py", line 170, in init
    self.init_templates()
  File "/home/vscode/.local/lib/python3.10/site-packages/sphinx/builders/html/__init__.py", line 224, in init_templates
    self.theme = theme_factory.create(theme_name)
  File "/home/vscode/.local/lib/python3.10/site-packages/sphinx/theming.py", line 236, in create
    raise ThemeError(__('no theme named %r found (missing theme.toml?)') % name)
sphinx.errors.ThemeError: no theme named 'sphinx_rtd_theme' found (missing theme.toml?)
```
```


### (Optional) Settings from conf.py

_No response_

**Comment by alexanderilyin** [comment]
Okay, so far it looks like problems with deps / settings on my side, looking.

**Comment by alexanderilyin** [comment]
I got this far, it happens when I try to open live preview:
```
[esbonio.lsp] Getting initial doctree for: '/workspaces/partcad/docs/source/development.rst'
Cancel notification for unknown message id "3"
Cancel notification for unknown message id "4"
stamina.retry_scheduled
stamina.retry_scheduled
stamina.retry_scheduled
[client] Ignoring file:///workspaces/partcad/docs/source/development.rst
[client] HTML Path 'undefined'
[client] Ignoring output:extension-output-swyddfa.esbonio-%231-Esbonio
stamina.retry_scheduled
```

**Comment by alcarney** [comment]
```
[client] Ignoring file:///workspaces/partcad/docs/source/development.rst
[client] HTML Path 'undefined'
```
Looks like the extension wasn't able to find the html file that corresponds to your `development.rst` file - has the extension managed to do a complete build?

It's been a while since I've used the `0.11.0` version, there's a chance you need edit a file and save it to start one going.

**Comment by alexanderilyin** [comment]
Nope, but I later learned that there were some other problems in my env, and docs were not building from CLI. I fixed that but not yet tried VS Code Extension after that, should come back to that in few days and report back.

**Comment by drew-hoffman** [comment]
I'm still getting this error in VS Code using Esbonio and RST Preview. Is there any resolution for it yet?

**Comment by shadowfax65** [comment]
I am having the same issue: `ModuleNotFoundError: No module named 'sphinx_rtd_theme'`

The folder is there but in `/home/bernd/.local/lib/python3.10/site-packages` which $PYTHONPATH points to. I can also build pages with sphinx via CLI without any issues, but the preview in VSC doesn't work at all.

Deinstalled and installed Esbonio 1.0 but to no avail. I am on Pop!_OS using VSCode version 1.106.3

Any help is appreciated! Thanks!

**Comment by alcarney** [comment]
Hi @shadowfax65!

> but the preview in VSC doesn't work at all.

I would have expected Esbonio to at least try using its fallback environment (so you'd see your docs with Sphinx's default theme), so if you can, setting `esbonio.logging.level` to `debug` sharing any log messages from Esbonio's Output window would be useful.

> The folder is there but in `/home/bernd/.local/lib/python3.10/site-packages/`

Is that where `pip install --user` saves to? I'll admit, it's not a use case I've considered... the value of `PYTHONPATH` is likely being ignored by the extension's default setup! 😅

If there is an executable in `/home/bernd/.local/bin/python` you might want to try something like this in your settings.json file.
```
{
   "esbonio.sphinx.pythonCommand": ["/home/bernd/.local/bin/python"]
}
```

Failing that, you can try setting the `PYTHONPATH` variable explicitly in the config

```
    "esbonio.sphinx.pythonCommand": {
        "command": ["python"],
        "env": {
            "PYTHONPATH": "/home/bernd/.local/lib/python3.10/site-packages"
        }
    }
```
Hope that helps!

**Comment by shadowfax65** [comment]
Thank you so much, @alcarney!

This fixed it: `Failing that, you can try setting the PYTHONPATH variable explicitly in the config`. The only thing I had to adjust was to change `python` into `python3` (seems to be the standard executable for Python 3 on Linux).

**Comment by Merlimau** [comment]
I can confirm this fixes the issue under Windows VSCode too : `ModuleNotFoundError: No module named 'sphinx_rtd_theme'`
It looks like Esobonio doesn’t check the PATH variables in Windows setup.
I have now the following content of `settings.json` in the `.vscode` folder:

```
{
 "esbonio.sphinx.pythonCommand":
        "command": ["python"],
        "env": {
            "PYTHONPATH": "C:\Users\Customer\AppData\Local\Programs\Python\Python310\Lib\site-packages"
        },
    "esbonio.sphinx.buildDir" : "${workspaceFolder}/build/html",
    "esbonio.sphinx.confDir"  : "${workspaceFolder}",
    "esbonio.sphinx.srcDir"   : "${workspaceFolder}"
}
```

Python can be installed for all users or only for a specific user. My setup is for a specific user, this is why Python is in AppData installed.

**Comment by MarcelloPerathoner** [comment]
I can confirm this bug and the workaround: to find `sphinx_rtd_theme` I had to explicitly set `PYTHONPATH` in `pyproject.toml` even if the theme is installed in the virtualenv used.
```
[tool.esbonio.sphinx.pythonCommand]
command = ["${venv:../../../.venv}"]
env = { PYTHONPATH = "../../../.venv/lib/python3.13/site-packages" }
```

**Comment by psam44** [comment]
I have a similar problem:
```
Running Sphinx v8.1.3
...
ThemeError: no theme named 'furo' found (missing theme.toml?)
Retrying with html_theme = 'alabaster'
```
Output traces show that, by default, the configuration is:
```
env={'PYTHONPATH': 'c:\\Users\\<user>\\.vscode\\extensions\\swyddfa.esbonio-2.0.0\\bundled\\env'}
```
At this location, there are ``alabaster-1.0.0.dist-info`` and ``sphinx-8.1.3.dist-info``, and obviously no furo (nor sphinx_rtd_theme).

Now, with this addition in my ``.vscode\settings.json``:
```
{
    "esbonio.sphinx.pythonCommand": {
        "env": {"PYTHONPATH": "C:\\Program Files\\Python313\\Lib\\site-packages"}
    }
}
```
The configuration becomes:
```
env={'PYTHONPATH': 'C:\\Program Files\\Python313\\Lib\\site-packages'}
```
And everything is fine:
```
Running Sphinx v8.2.3
...
```
Just because at this place, there are my own installs: ``furo-2025.9.25.dist-info`` and ``sphinx-8.2.3.dist-info``.

Is there a better approach to solve the issue?

**Comment by alcarney** [comment]
> Is there a better approach to solve the issue?

It depends on what you mean by "better".

It's generally expected that you will need to set the `esbonio.sphinx.pythonCommand` to point Esbonio at the dependencies for your project. The environment bundled with the extension is only intended as a fallback so the extension can still make some progress without an explicit configuration.

If by "better" you mean more something less specific to your machine, then you could investigate using a tool like `hatch` to define all the dependencies needed to build your docs, and then point Esbonio at that environment. You can find examples of this [here](https://docs.esbon.io/en/latest/usage/howto/configure-the-sphinx-build-env.html)

It would be nice if it wasn't necessary to configure PYTHONPATH explicitly when using user-level/global environments, but I haven't got around to checking if there's anything Esbonio can do to fix it.

Hope that helps!

**Comment by psam44** [comment]
PYTHONPATH is supposed to **add** entries to the search path.
The search path has a default installation-dependant pre-list. For example, it may include these:
```
'C:\\Program Files\\Python313\\Lib\\idlelib',
'C:\\Program Files\\Python313\\python313.zip',
'C:\\Program Files\\Python313\\DLLs',
'C:\\Program Files\\Python313\\Lib',
'C:\\Program Files\\Python313',
'C:\\Program Files\\Python313\\Lib\\site-packages',
```

But the default configuration is: `command=['c:\\Program Files\\Python313\\python.exe', '-S'],`. The `-S` option disables these default entries (for isolation reasons, as seen in comments in the sources, but maybe related to the Language Server).

If I set in my .vscode\settings.json:
```
{
    "esbonio.sphinx.pythonCommand": {
        "command": []
    }
}
```

It's enough to have:
```
[workspace/didChangeConfiguration()][esbonio.Configuration] ConfigChangeEvent(
...
value=SphinxConfig(enable_dev_tools=False, python_command=SubProcess(
 command=[],
 env={'PYTHONPATH': 'c:\\Users\\Patrick\\.vscode\\extensions\\swyddfa.esbonio-2.0.0\\bundled\\env'},
...),...)
[workspace/didChangeConfiguration()][esbonio.SphinxManager] No pythonCommand configured! Reusing the server's environment.
Running Sphinx v8.1.3
```

In that case Sphinx is found in priority in the fallback env (may be desirable or not) and furo can be found in the system site-packages.

With:
```
{
    "esbonio.sphinx.pythonCommand": {
        "command": [],
        "env": {"PYTHONPATH": ""}
    }
}
```
I even benefit of a more recent Sphinx version (without to cite host specific locations):
```
[workspace/didChangeConfiguration()][esbonio.SphinxManager] No pythonCommand configured! Reusing the server's environment.
Running Sphinx v8.2.3
```

**Comment by alcarney** [comment]
> But the default configuration is: `command=['c:\\Program Files\\Python313\\python.exe', '-S'],`. The `-S` option disables these default entries (for isolation reasons, as seen in comments in the sources, but maybe related to the Language Server).

When implementing the fallback environment I simply reused the "trick" I'd found with `-S` without much thought, as it allowed the extension to take any Python interpreter and point it at an environment of its choosing.

While I think this still makes sense for the server's environment, as you've pointed out, it probably makes less sense for the fallback Sphinx environment...

> If I set in my .vscode\settings.json:
> ```
> {
>    "esbonio.sphinx.pythonCommand": {
>        "command": []
>    }
> }
> ```

> It's enough to have:
> ```
> [workspace/didChangeConfiguration()][esbonio.SphinxManager] No pythonCommand configured! Reusing the server's environment.
> Running Sphinx v8.1.3
> ```

> In that case Sphinx is found in priority in the fallback env (may be desirable or not) and furo can be found in the system site-packages.

I wonder if it's possible to add the fallback env to the path in a way so that it's a lower priority than the user env, that way it truly would be a fallback environment 🤔

**Comment by psam44** [comment]
Here is a hint implemented in `esbonio\sphinx_agent\__main__.py`.
Note: It can't be done in `__init__.py` because this file is also imported on the `esbonio\server\` side for `.types` usage.

```
import asyncio

from .server import main

# <add>
import importlib.util
import logging
import sys
logger = logging.getLogger("psam")

logger.warning('sphinx %s', importlib.util.find_spec('sphinx'))
# ModuleSpec(... origin='c:\\Program Files\\Python313\\Lib\\site-packages\\sphinx\\__init__.py' ...)
# Python is run without '-S' ; Here, Sphinx is found because it is already available in the host installation
# For the demo when the host doesn't have Sphinx, let's substitute it with another unknown package (tomli in my case)
tomli_spec = importlib.util.find_spec('tomli')
logger.warning('tomli %s', tomli_spec)  # None
if tomli_spec is None:
    # Add the fallback env ; here hardcoded for demo
    # Equivalent to vscode3.Uri.joinPath(this.extensionUri, "bundled", "env").fsPath of code/src/node/client.ts
    # How to get it cleanly? may be through an Esbonio-specific environment variable
    sys.path.append("c:\\Users\\Patrick\\.vscode\\extensions\\swyddfa.esbonio-2.0.0\\bundled\\env")
    logger.warning('tomli %s', importlib.util.find_spec('tomli'))
    # ModuleSpec(... origin='c:\\Users\\Patrick\\.vscode\\extensions\\swyddfa.esbonio-2.0.0\\bundled\\env\\tomli\\__init__.py' ...)
    # From there, any "from sphinx import" should success
# </add>

asyncio.run(main())
```

**Comment by alcarney** [comment]
Thanks for the example! It's definitely got me thinking, I've captured some thoughts in #1112.
